# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Challenge 7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Challenge 7
pod 'RealmSwift', '=10.1.4'
pod 'SwipeCellKit'


end
